services:
  mqtt:
    image: eclipse-mosquitto:2.0.18-openssl
    container_name: mqtt
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - $PWD/mosquitto/config:/mosquitto/config
      - mqtt_data:/mosquitto/data

  grafana:
    image: grafana/grafana-oss:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
    #  - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
      - TZ=Asia/Tokyo
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    volumes:
      - grafana_data:/var/lib/grafana

  node-red:
    image: nodered/node-red:3.1.3
    container_name: node-red
    ports:
      - "1880:1880"
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - node_red_data:/data

  influxdb2:
    image: influxdb:2.7.4
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - $PWD/influxdb2/config:/etc/influxdb2

volumes:
  mqtt_data:
  grafana_data:
  node_red_data:
  influxdb2_data:
